name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Flutter action
      uses: subosito/flutter-action@v2.18.0

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Verify Flutter Installation
      run: flutter doctor

    - name: Create Missing Flutter Files
      run: flutter create .

    - name: Install Dependencies
      run: flutter pub get

    - name: Upgrade Flutter
      run: flutter upgrade

    - name: Analyze Code
      run: flutter analyze

    - name: Run Tests
      run: flutter test

    - name: Setup Java JDK
      uses: actions/setup-java@v4.7.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8

    - name: Setup Go environment
      uses: actions/setup-go@v5.3.0
