name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Setup Flutter
    - name: Flutter action
      uses: subosito/flutter-action@v2.18.0

    # 2. Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 3. Verify Flutter Installation
    - name: Verify Flutter Installation
      run: flutter doctor

    # 4. Create Missing Flutter Files (Optional)
    - name: Create Missing Flutter Files
      run: flutter create .

    # 5. Install Dependencies
    - name: Install Dependencies
      run: flutter pub get

    # 6. Upgrade Flutter and Dependencies
    - name: Upgrade Flutter
      run: flutter upgrade

    # 7. Run lint checks
    - name: Analyze Code
      run: flutter analyze

    # 8. Run tests
    - name: Run Tests
      run: flutter test

    - name: Setup Java JDK
      uses: actions/setup-java@v4.7.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8

    - name: Setup Go environment
      uses: actions/setup-go@v5.3.0

      

 
