name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Unit Tests
      run: flutter test
