name: Update Documentation

on:
  push:
    paths:
      - 'README.md'

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Commit Changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add README.md
        git commit -m "Update Documentation [skip ci]"
        git push
